# DAILY VALUE
DV_CALORIES = 2000
DV_CARBS = 275
DV_FAT = 78
DV_PROTEIN = 50
DV_SODIUM = 2300
DV_SUGAR = 50
DV_FIBER = 28
DV_SATURATED_FAT = 20
DV_CHOLESTEROL = 300

# DB INFO
AWS_ACCESS_KEY = 'AKIAUQ5RSVGJSYOLOFNE'
AWS_SECRET_KEY = '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'
REGION_NAME = 'us-east-2'

# TABLES
RECIPE_TABLE = 'recipe'
RECIPE_STATS_TABLE = 'recipe_stats'

# URLS
FOOD_NETWORK_URL = 'https://www.foodnetwork.com/recipes/recipes-a-z'