
class Recipe:
    id: int
    title: str
    source: str
    site_name: str
    url: str
    servings: str
    image: str
    rating: float
    total_time: str
    prep_time: str
    cook_time: str
    calories: int
    total_fat: int
    saturated_fat: int
    carbs: int
    fiber: int
    sugar: int
    protein: int
    cholesterol: int
    sodium: int
    ingredients: [str]
