from enum import Enum
from constants import *


class WikibooksUrl(Enum):
    URL_1 = WIKIBOOKSURL_1
    URL_2 = WIKIBOOKSURL_2
    URL_3 = WIKIBOOKSURL_3
    URL_4 = WIKIBOOKSURL_4
    URL_5 = WIKIBOOKSURL_5
    URL_6 = WIKIBOOKSURL_6
    URL_7 = WIKIBOOKSURL_7
    URL_8 = WIKIBOOKSURL_8
    URL_9 = WIKIBOOKSURL_9
    URL_10 = WIKIBOOKSURL_10
    URL_11 = WIKIBOOKSURL_11
    URL_12 = WIKIBOOKSURL_12
    URL_13 = WIKIBOOKSURL_13
    URL_14 = WIKIBOOKSURL_14
    URL_15 = WIKIBOOKSURL_15
    URL_16 = WIKIBOOKSURL_16
    URL_17 = WIKIBOOKSURL_17
    URL_18 = WIKIBOOKSURL_18
    URL_19 = WIKIBOOKSURL_19
    URL_20 = WIKIBOOKSURL_20
